---
- name: Install other packages
  apt:
    name: ['unzip', 'git', 'snapd', 'make', 'fuse3']
    state: latest 
    update_cache: yes 
    cache_valid_time: 3600

- name: Install go with snap
  snap: name=go classic=yes
    
- name: Creates directories for git clone
  file: path={{ item.path}} state=directory
  with_items:
    - { path: "{{snapshotter_path}}/cvmfs-devel" }
    - { path: "{{snapshotter_path}}/nerdctl" }

- name: Check if nerdctl is already installed
  stat:
    path: /usr/local/bin/nerdctl
  register: ndctl
    
- name: Clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/containerd/nerdctl", dest: "{{snapshotter_path}}/nerdctl", version: "v1.7.7", depth: 1 }
  when: not ndctl.stat.exists

- name: Download and unarchive cvmfs-devel
  unarchive:
    src: https://github.com/cvmfs/cvmfs/archive/refs/heads/devel.zip
    dest: "{{snapshotter_path}}"
    remote_src: yes
  
- name: Build snapshotter 
  command: make chdir={{snapshotter_path}}/cvmfs-devel/snapshotter
  environment: 
    PATH: /snap/bin:{{ ansible_env.PATH }}
    PREFIX: "/usr/local/bin/"
    VERSION: "{{snapshotter_version}}"
    
- name: Build nerdctl
  command: make chdir={{snapshotter_path}}/nerdctl
  environment: 
    PATH: /snap/bin:{{ ansible_env.PATH }}
  when: not ndctl.stat.exists
- command: make install chdir={{snapshotter_path}}/nerdctl
  when: not ndctl.stat.exists
